// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var $errJSON, $loading, clearFacebookInfo, getFacebook;
    $loading = $("#loading");
    $errJSON = $('#errJSON');
    getFacebook = function(id) {
      var fbid;
      fbid = id;
      return $.ajax({
        'url': 'http://graph.facebook.com/',
        'method': 'get',
        'data': {
          'id': fbid
        },
        'beforeSend': function() {
          $loading.css('opacity', 1);
          $errJSON.css('opacity', 0);
          return clearFacebookInfo();
        }
      }).fail(function(err) {
        $errJSON.css('opacity', $errJSON.html(err.responseText));
        return $loading.css('opacity', 0);
      }).success(function(data) {
        $("#firstname").html(data.first_name);
        $("#lastname").html(data.last_name);
        $("#gender").html(data.gender);
        $loading.css('opacity', 0);
        return $errJSON.css('opacity', 0);
      });
    };
    $('.form-control').on("input", function() {
      return getFacebook($(this).val());
    });
    return clearFacebookInfo = function() {
      var item, items, _i, _len, _results;
      items = ["#firstname", "#lastname", "#gender"];
      _results = [];
      for (_i = 0, _len = items.length; _i < _len; _i++) {
        item = items[_i];
        _results.push($(item).html(""));
      }
      return _results;
    };
  });

}).call(this);

//# sourceMappingURL=ajax.map
